CREATE DATABASE leader_db
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE leader_db;

CREATE TABLE products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(128) NOT NULL,
	price INT NOT NULL,
	image VARCHAR(128)
);